version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: rbpl-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=rbpl
        - MYSQL_USER=rbpl
        - MYSQL_PASSWORD=rbpl
      ports:
        - "8002:3306"
      networks:
        - rbpl

    webserver:
      image: nginx:alpine
      container_name: rbpl-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
      depends_on:
       - mysql
      networks:
       - rbpl

    php-fpm:
      build: docker/php-fpm
      container_name: docker-symfony4-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
       - mysql
      networks:
       - rbpl

networks:
    rbpl:
      external:
        name: shop-local

